version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
  webauthent:
    image: ${DOCKER_REGISTRY-}webauthent
    build:
      context: .
      dockerfile: WebAuthent/Dockerfile
  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: WebMvc/Dockerfile
