FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["TestProj/TestProj.csproj", "TestProj/"]
RUN dotnet restore "TestProj/TestProj.csproj"
COPY . .
WORKDIR "/src/TestProj"
RUN dotnet build "TestProj.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "TestProj.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "TestProj.dll"]